def main():
    print()
    print("You take a peek at the lease.")
    print("It's mostly boilerplate--no pets, apparently--but you don't actually see anywhere to sign the dang thing...")
    print()
    print("Though there's this one weird section at the end, that reads: ")
    print()
    print("TO AFFIRM YOUR USER IDENTITY, ENTER THE FOLLOWING COMMAND IN YOUR TERMINAL WINDOW")
    print("BUT REPLACE THE TEXT IN QUOTES WITH YOUR ALLEGHENY EMAIL ADDRESS (LEAVE THE QUOTE MARKS)")
    print()
    print('git config --global user.email "YOUR ALLEGHENY EMAIL"')
    print()
    print("THEN, TO ASSIGN YOUR NAME TO THIS HOUSE AND ALL THE WORK DONE WITHIN IT (AND WITHOUT)")
    print("ENTER THIS NEXT COMMAND IN YOUR TERMINAL WINDOW,")
    print("THIS TIME REPLACING THE TEXT IN QUOTES WITH YOUR GITHUB USERNAME (LEAVE THE QUOTE MARKS)")
    print()
    print('git config --global user.name "YOUR GITHUB USERNAME"')
    print()
    print("THESE ACTIONS ONLY HAVE TO BE TAKEN ONCE. THANK YOU.")
    print()
    print("~Once you've entered the above two commands, you may want to mark off the appropriate to-do on the fridge list~")
    print()

if __name__ == "__main__":
    main()